
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WindowsFormsApp6
{

using System;
    using System.Collections.Generic;
    
public partial class EMP_TABLE
{

    public int EMP_ID { get; set; }

    public string EMP_NAME { get; set; }

    public string DESIGNATION { get; set; }

    public string BIKE_NO { get; set; }

}

}
